version: '3'

services:

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - nodenet

  app:
    build:
      context: ./node-app
      dockerfile: Dockerfile
    image: souojor/nodeapp
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s node index.js
    networks:
      - nodenet
    volumes:
      - ./node-app/src:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    tty: true
    depends_on:
      - db
  
  nginx:
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: souojor/nginx
    container_name: nginx
    networks:
      - nodenet
    ports:
      - "8080:80"

networks:
  nodenet:
    driver: bridge

volumes:
  node_modules:

#docker-compose up -d
#docker-compose down
#docker-compose up -d --build